/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author USUARIO
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnbMenu = new javax.swing.JMenuBar();
        mnuMantenedor = new javax.swing.JMenu();
        mnuCliente = new javax.swing.JMenu();
        mniPersonas = new javax.swing.JMenuItem();
        mniEmpresas = new javax.swing.JMenuItem();
        mnuCuentas = new javax.swing.JMenu();
        mniCuentaCorriente = new javax.swing.JMenuItem();
        mniCuentaAhorro = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco XYZ");

        mnuMantenedor.setMnemonic('M');
        mnuMantenedor.setText("Mantenedores");

        mnuCliente.setMnemonic('C');
        mnuCliente.setText("Clientes");

        mniPersonas.setMnemonic('P');
        mniPersonas.setText("Personas");
        mniPersonas.setToolTipText("");
        mnuCliente.add(mniPersonas);

        mniEmpresas.setMnemonic('E');
        mniEmpresas.setText("Empresas");
        mnuCliente.add(mniEmpresas);

        mnuMantenedor.add(mnuCliente);

        mnuCuentas.setText("Cuentas");

        mniCuentaCorriente.setText("Cuenta Corriente");
        mnuCuentas.add(mniCuentaCorriente);

        mniCuentaAhorro.setText("Cuenta Ahorro");
        mnuCuentas.add(mniCuentaAhorro);

        mnuMantenedor.add(mnuCuentas);

        mnbMenu.add(mnuMantenedor);

        mnuAyuda.setText("Ayuda");
        mnbMenu.add(mnuAyuda);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniCuentaAhorro;
    private javax.swing.JMenuItem mniCuentaCorriente;
    private javax.swing.JMenuItem mniEmpresas;
    private javax.swing.JMenuItem mniPersonas;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenu mnuCuentas;
    private javax.swing.JMenu mnuMantenedor;
    // End of variables declaration//GEN-END:variables
}
