/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author ramos
 */
public class IfrmEmitirCheques extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmEmitirCheques
     */
    public IfrmEmitirCheques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmitirCheque = new javax.swing.JLabel();
        lblMontoCheque = new javax.swing.JLabel();
        txtMontoChequera = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnEmitirCheque = new javax.swing.JButton();

        lblEmitirCheque.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblEmitirCheque.setText("EMITIR CHEQUE");

        lblMontoCheque.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblMontoCheque.setText("Monto: ");

        btnVolver.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnEmitirCheque.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnEmitirCheque.setText("Emitir");
        btnEmitirCheque.setEnabled(false);
        btnEmitirCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirChequeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblEmitirCheque))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEmitirCheque))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMontoCheque)
                                .addGap(18, 18, 18)
                                .addComponent(txtMontoChequera, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmitirCheque)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoCheque)
                    .addComponent(txtMontoChequera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnEmitirCheque))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEmitirChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirChequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmitirChequeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmitirCheque;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblEmitirCheque;
    private javax.swing.JLabel lblMontoCheque;
    private javax.swing.JTextField txtMontoChequera;
    // End of variables declaration//GEN-END:variables
}
