/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import entidades.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author ramos
 */
public class IfrmRetirar extends javax.swing.JInternalFrame {
Cuenta cuenta;
    /**
     * Creates new form IfrmRetirar
     */
    public IfrmRetirar(Cuenta cuenta) {
        initComponents();
        
        this.cuenta = cuenta;
        lblSaldoCuenta.setText(String.valueOf(cuenta.getSaldoCuenta()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRetiro = new javax.swing.JLabel();
        lblSaldoActual = new javax.swing.JLabel();
        lblSaldoCuenta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnOcultar = new javax.swing.JButton();
        lblIngreseMonto = new javax.swing.JLabel();
        txtSaldoRetiro = new javax.swing.JTextField();
        btnRetirar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        lblRetiro.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblRetiro.setText("RETIRO");

        lblSaldoActual.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSaldoActual.setText("Saldo Actual:");

        lblSaldoCuenta.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblSaldoCuenta.setText("0.0");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblIngreseMonto.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblIngreseMonto.setText("Ingrese monto a Retirar:");

        txtSaldoRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoRetiroActionPerformed(evt);
            }
        });
        txtSaldoRetiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoRetiroKeyTyped(evt);
            }
        });

        btnRetirar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblSaldoActual)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblIngreseMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(txtSaldoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(btnVolver)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRetirar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblRetiro)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRetiro)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSaldoActual)
                        .addComponent(lblSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngreseMonto)
                    .addComponent(txtSaldoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar)
                    .addComponent(btnVolver))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoRetiroActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        float montoRetiro = Float.parseFloat(txtSaldoRetiro.getText());
        if(cuenta.realizarRetiro(montoRetiro)){
            JOptionPane.showMessageDialog(null, "Dinero retirado");
            this.dispose();
        }
        else JOptionPane.showMessageDialog(null, "No cuenta con suficiente saldo ");
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtSaldoRetiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoRetiroKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoRetiroKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOcultar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIngreseMonto;
    private javax.swing.JLabel lblRetiro;
    private javax.swing.JLabel lblSaldoActual;
    private javax.swing.JLabel lblSaldoCuenta;
    private javax.swing.JTextField txtSaldoRetiro;
    // End of variables declaration//GEN-END:variables
}
