/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import datos.ListaCuentas;
import entidades.Cuenta;
import entidades.CuentaCorriente;
import entidades.CuentaCorriente.Chequera;
import entidades.CuentaCorriente.Chequera.Cheque;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author ramos
 */
public class IfrmCobrarCheque extends javax.swing.JInternalFrame {
    private ListaCuentas listaC = ListaCuentas.cargarCuentas("src/datos/DatosCuentas.dat");
    Cuenta cuenta;
    /**
     * Creates new form IfrmCobrarCheque
     */
    public IfrmCobrarCheque(Cuenta cuenta) {
        initComponents();
        this.cuenta= cuenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTransferencia = new javax.swing.JLabel();
        lblMontoCheque = new javax.swing.JLabel();
        txtNumeroChequera = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnCobrarCheque = new javax.swing.JButton();

        lblTransferencia.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblTransferencia.setText("COBRAR CHEQUE");

        lblMontoCheque.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblMontoCheque.setText("N° de Cheque: ");

        btnVolver.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnCobrarCheque.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCobrarCheque.setText("Cobrar");
        btnCobrarCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarChequeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblTransferencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblMontoCheque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroChequera, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(btnVolver)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCobrarCheque)
                    .addGap(35, 35, 35)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTransferencia)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoCheque)
                    .addComponent(txtNumeroChequera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVolver)
                        .addComponent(btnCobrarCheque))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCobrarChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarChequeActionPerformed
        Cuenta cuentaB;
        String numeroCheque = txtNumeroChequera.getText();
        int posicionCuenta = listaC.buscarChequeraCuentaCorriente(numeroCheque);
        if (posicionCuenta!=-1){
            cuentaB = listaC.obtenerCuenta(posicionCuenta);
            int posicionChequera = ((CuentaCorriente)cuentaB).buscarChequeTodasChequeras(numeroCheque);
            Chequera chequera = ((CuentaCorriente)cuentaB).obtenerChequera(posicionChequera);
            int posicionCheque = chequera.buscarCheque(numeroCheque);
            Cheque cheque = chequera.obtenerCheque(posicionCheque);
            System.out.println("\nmonto:"+cheque.getMonto());
            if(cuenta.cobroCheques(cheque.getMonto())){
                if(((CuentaCorriente)cuentaB).cobrarChequera(posicionChequera,posicionCheque, cheque.getMonto())){
                    JOptionPane.showMessageDialog(null, "Se cobro con exito el cheque: ");
                    listaC.guardarEnArchivo("src/datos/DatosCuentas.dat");
                }
                
                
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No se encontro el numero de cheque solicitado ");
        }
    }//GEN-LAST:event_btnCobrarChequeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrarCheque;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblMontoCheque;
    private javax.swing.JLabel lblTransferencia;
    private javax.swing.JTextField txtNumeroChequera;
    // End of variables declaration//GEN-END:variables
}
