/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import entidades.Cuenta;
import javax.swing.*;

/**
 *
 * @author ramos
 */
public class IfrmDeposito extends javax.swing.JInternalFrame {
    Cuenta cuenta;
    /**
     * Creates new form IfrmDepositar
     */
    public IfrmDeposito(Cuenta cuenta) {
        this.cuenta = cuenta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeposito = new javax.swing.JLabel();
        lblSaldoActual1 = new javax.swing.JLabel();
        txtSaldoDeposito = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        lblDeposito.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblDeposito.setText("DEPOSITO");

        lblSaldoActual1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSaldoActual1.setText("Ingrese Saldo a Depositar:");

        btnDepositar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnDepositar.setText("Deposito");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblDeposito))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblSaldoActual1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(txtSaldoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnCerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDepositar)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeposito)
                .addGap(18, 18, 18)
                .addComponent(lblSaldoActual1)
                .addGap(18, 18, 18)
                .addComponent(txtSaldoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositar)
                    .addComponent(btnCerrar))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        float montoDeposito = Float.parseFloat(txtSaldoDeposito.getText());
        if(cuenta.realizarDeposito(montoDeposito)){
            JOptionPane.showMessageDialog(this, "Deposito realizado con exito ", "Deposito", 2);
            
        }
        
        this.dispose();
        
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JLabel lblDeposito;
    private javax.swing.JLabel lblSaldoActual1;
    private javax.swing.JTextField txtSaldoDeposito;
    // End of variables declaration//GEN-END:variables
}
