/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import entidades.*;
import entidades.Cuenta.Operaciones;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JuanMistery
 */
public class ifrmOperaciones extends javax.swing.JInternalFrame {

    private ArrayList<Operaciones> listaOperaciones;

       public ifrmOperaciones(Cuenta cuenta) {
        initComponents();
        listaOperaciones = new ArrayList<>(cuenta.getOperaciones());
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Número de Operación");
        model.addColumn("Fecha de Operación");
        model.addColumn("Tipo de Operación");
        model.addColumn("Monto de Operación");

                for (Operaciones operacion : listaOperaciones) {
            String numeroOperacion = operacion.getNumeroOperacion();
            String fechaOperacion = operacion.getFechaOperacionCorta();
            int tipoOperacion = operacion.getTipoOperacion();
            float montoOperacion = operacion.getMontoOperacion();

            model.addRow(new Object[]{numeroOperacion, fechaOperacion, tipoOperacion, montoOperacion});
        }
         jTable1.setModel(model);
    }
    private String obtenerNombreTipo(int tipoOperacion) {
        switch (tipoOperacion) {
            case 1:
                return "Depósito";
            case 2:
                return "Retiro";
            case 3:
                return "Transferencia";
            case 4:
                return "ITF";
            case 5:
                return "Interés Mensual";
            default:
                return "Desconocido";
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Operaciones");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
