/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import javax.swing.*;
import adicionales.*;
/**
 *
 * @author ramos
 */
public class ifrmCuentaAhorro extends javax.swing.JInternalFrame {
    Escalar escalar = new Escalar();
    
    
    /**
     * Creates new form MostrarDatosDeCuentaAhorro
     */
    public ifrmCuentaAhorro() {
        initComponents();
        escalar.escalarBoton(btnNotificacion, "imagenes/image-removebg-previw.png");
        escalar.escalarLabel(lblIcon, "imagenes/logo_interbank.jpg");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBienvenida = new javax.swing.JPanel();
        lblCuentaAhorro = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        btnNotificacion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblSaldoActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        btnOcultar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        mnbMenu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuCuenta = new javax.swing.JMenu();
        mniInformacion = new javax.swing.JMenuItem();
        mniEstadoCuenta = new javax.swing.JMenuItem();
        mnuOperaciones = new javax.swing.JMenu();
        mniDepositar = new javax.swing.JMenuItem();
        mniRetirar = new javax.swing.JMenuItem();
        mniTransferencia = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panBienvenida.setBackground(new java.awt.Color(102, 255, 102));
        panBienvenida.setForeground(new java.awt.Color(51, 255, 51));

        lblCuentaAhorro.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        lblCuentaAhorro.setForeground(new java.awt.Color(255, 255, 255));
        lblCuentaAhorro.setText("CUENTA AHORRO");

        javax.swing.GroupLayout panBienvenidaLayout = new javax.swing.GroupLayout(panBienvenida);
        panBienvenida.setLayout(panBienvenidaLayout);
        panBienvenidaLayout.setHorizontalGroup(
            panBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBienvenidaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(lblCuentaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(btnNotificacion)
                .addGap(29, 29, 29))
        );
        panBienvenidaLayout.setVerticalGroup(
            panBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBienvenidaLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBienvenidaLayout.createSequentialGroup()
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBienvenidaLayout.createSequentialGroup()
                        .addGroup(panBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCuentaAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))))
        );

        getContentPane().add(panBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 769, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSaldoActual.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblSaldoActual.setText("SALDO ACTUAL");

        jLabel1.setText("0.00");

        lblBienvenido.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblBienvenido.setText("BIENVENIDO ");

        lblNombres.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNombres.setText("Nombre de usuario gaaaaaaaaaa");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaldoActual)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(131, 131, 131))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 500));

        mnbMenu.add(jMenu2);

        mnuCuenta.setText("Cuenta");

        mniInformacion.setText("Información");
        mniInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInformacionActionPerformed(evt);
            }
        });
        mnuCuenta.add(mniInformacion);

        mniEstadoCuenta.setText("Estado de Cuenta");
        mniEstadoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEstadoCuentaActionPerformed(evt);
            }
        });
        mnuCuenta.add(mniEstadoCuenta);

        mnbMenu.add(mnuCuenta);

        mnuOperaciones.setText("Operaciones");

        mniDepositar.setText("Depositar");
        mniDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDepositarActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mniDepositar);

        mniRetirar.setText("Retirar");
        mnuOperaciones.add(mniRetirar);

        mniTransferencia.setText("transferencia");
        mnuOperaciones.add(mniTransferencia);

        mnbMenu.add(mnuOperaciones);

        setJMenuBar(mnbMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniInformacionActionPerformed

    private void mniEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEstadoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniEstadoCuentaActionPerformed

    private void mniDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDepositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDepositarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotificacion;
    private javax.swing.JButton btnOcultar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCuentaAhorro;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblSaldoActual;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniDepositar;
    private javax.swing.JMenuItem mniEstadoCuenta;
    private javax.swing.JMenuItem mniInformacion;
    private javax.swing.JMenuItem mniRetirar;
    private javax.swing.JMenuItem mniTransferencia;
    private javax.swing.JMenu mnuCuenta;
    private javax.swing.JMenu mnuOperaciones;
    private javax.swing.JPanel panBienvenida;
    // End of variables declaration//GEN-END:variables


    class imagenPanel extends JPanel{
        
    }
           
}

