/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import javax.swing.JTextField;

/**
 *
 * @author JuanMistery
 */
public class panCuentaCorriente extends javax.swing.JPanel {

    /**
     * Creates new form panCuentaCorriente
     */
    public panCuentaCorriente() {
        initComponents();
    }

    public String getTxtLimiteDeEmision() {
        return txtLimiteDeEmision.getText();
    }

    public String getTxtLimiteDeSobregiro() {
        return txtLimiteDeSobregiro.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLimiteDeSobregiro = new javax.swing.JLabel();
        lblLimiteDeEmision = new javax.swing.JLabel();
        txtLimiteDeSobregiro = new javax.swing.JTextField();
        txtLimiteDeEmision = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));

        lblLimiteDeSobregiro.setText("Limite de Sobregiro:");

        lblLimiteDeEmision.setText("Limite de Emision de Cheques:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLimiteDeEmision)
                        .addGap(18, 18, 18)
                        .addComponent(txtLimiteDeEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLimiteDeSobregiro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLimiteDeSobregiro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteDeSobregiro)
                    .addComponent(txtLimiteDeSobregiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteDeEmision)
                    .addComponent(txtLimiteDeEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLimiteDeEmision;
    private javax.swing.JLabel lblLimiteDeSobregiro;
    private javax.swing.JTextField txtLimiteDeEmision;
    private javax.swing.JTextField txtLimiteDeSobregiro;
    // End of variables declaration//GEN-END:variables
}
