/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import entidades.*;
import java.util.ArrayList;

import javax.swing.JTextField;

/**
 *
 * @author JuanMistery
 */
public class panCuentaAhorro extends javax.swing.JPanel {
    
    private panBeneficiarios panelBeneficiarios;
    
    /**
     * Creates new form panCuentaAhorro
     */
    public panCuentaAhorro() {
        initComponents();
        actualizarPanelBeneficiarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public String getTxtLimiteRetiro() {
        return txtLimiteRetiro.getText();
    }
    
    public ArrayList<Persona> getListaPersona()
    {
        return panelBeneficiarios.recuperarListaP();
    }

    private void actualizarPanelBeneficiarios() {
        // Remover todos los componentes actuales del panel
        panForBeneficiarios.removeAll();

        // Crear una nueva instancia del panel de beneficiarios
        panelBeneficiarios = new panBeneficiarios();

        // Configurar el layout de panForBeneficiarios para acomodar el nuevo panel
        panForBeneficiarios.setLayout(new java.awt.BorderLayout());
        panForBeneficiarios.add(panelBeneficiarios, java.awt.BorderLayout.CENTER);

        // Volver a dibujar el panel
        panForBeneficiarios.revalidate();
        panForBeneficiarios.repaint();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLimiteRetiro = new javax.swing.JLabel();
        txtLimiteRetiro = new javax.swing.JTextField();
        panForBeneficiarios = new javax.swing.JPanel();

        lblLimiteRetiro.setText("Limite de Retiro: ");

        panForBeneficiarios.setMinimumSize(new java.awt.Dimension(400, 210));
        panForBeneficiarios.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout panForBeneficiariosLayout = new javax.swing.GroupLayout(panForBeneficiarios);
        panForBeneficiarios.setLayout(panForBeneficiariosLayout);
        panForBeneficiariosLayout.setHorizontalGroup(
            panForBeneficiariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panForBeneficiariosLayout.setVerticalGroup(
            panForBeneficiariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblLimiteRetiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(txtLimiteRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(panForBeneficiarios, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteRetiro)
                    .addComponent(txtLimiteRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panForBeneficiarios, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLimiteRetiro;
    private javax.swing.JPanel panForBeneficiarios;
    private javax.swing.JTextField txtLimiteRetiro;
    // End of variables declaration//GEN-END:variables
}
